# Generated by Django 6.0.7 on 2026-09-10 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmProductos',
            fields=[
                ('CIDPRODUCTO', models.AutoField(db_column='CIDPRODUCTO', primary_key=True, serialize=False)),
                ('CCODIGOPRODUCTO', models.CharField(db_column='CCODIGOPRODUCTO', max_length=30)),
                ('CNOMBREPRODUCTO', models.CharField(db_column='CNOMBREPRODUCTO', max_length=60)),
                ('CPRECIO1', models.FloatField(db_column='CPRECIO1')),
                ('CTEXTOEXTRA1', models.CharField(db_column='CTEXTOEXTRA1', max_length=50, null=True)),
            ],
            options={
                'db_table': 'admProductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmExistenciaCosto',
            fields=[
                ('CIDPRODUCTO', models.ForeignKey(db_column='CIDPRODUCTO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='existencias', serialize=False, to='api.admproductos')),
                ('CENTRADASINICIALES', models.FloatField(db_column='CENTRADASINICIALES')),
                ('CSALIDASINICIALES', models.FloatField(db_column='CSALIDASINICIALES')),
            ],
            options={
                'db_table': 'admExistenciaCosto',
                'managed': False,
            },
        ),
    ]
