# Generated by Django 6.0.7 on 2026-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('GEA', 'GEA'), ('Bionat Sano', 'Bionat Sano'), ('Animat', 'Animat'), ('VES-Artex', 'VES-Artex')], default='GEA', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sistemas de Ordeño', 'Sistemas de Ordeño'), ('Nutrición', 'Nutrición'), ('Refacciones', 'Refacciones'), ('Confort Animal', 'Confort Animal'), ('Almacenamiento', 'Almacenamiento')], default='Refacciones', max_length=50),
        ),
    ]
