# Generated by Django 6.0.7 on 2026-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmClasificacionesValores',
            fields=[
                ('CIDVALORCLASIFICACION', models.AutoField(db_column='CIDVALORCLASIFICACION', primary_key=True, serialize=False)),
                ('CVALORCLASIFICACION', models.CharField(db_column='CVALORCLASIFICACION', max_length=60)),
                ('CIDCLASIFICACION', models.IntegerField(db_column='CIDCLASIFICACION')),
            ],
            options={
                'db_table': 'admClasificacionesValores',
                'managed': False,
            },
        ),
    ]
