# Generated by Django 6.0.7 on 2026-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admclasificacionesvalores'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmAgentes',
            fields=[
                ('CIDAGENTE', models.AutoField(db_column='CIDAGENTE', primary_key=True, serialize=False)),
                ('CCODIGOAGENTE', models.CharField(db_column='CCODIGOAGENTE', max_length=30)),
                ('CNOMBREAGENTE', models.CharField(db_column='CNOMBREAGENTE', max_length=60)),
            ],
            options={
                'db_table': 'admAgentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmConceptos',
            fields=[
                ('CIDCONCEPTODOCUMENTO', models.AutoField(db_column='CIDCONCEPTODOCUMENTO', primary_key=True, serialize=False)),
                ('CPREFIJOCONCEPTO', models.CharField(db_column='CPREFIJOCONCEPTO', max_length=10, null=True)),
            ],
            options={
                'db_table': 'admConceptos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmDocumentos',
            fields=[
                ('CIDDOCUMENTO', models.AutoField(db_column='CIDDOCUMENTO', primary_key=True, serialize=False)),
                ('CIDDOCUMENTODE', models.IntegerField(db_column='CIDDOCUMENTODE')),
                ('CIDCONCEPTODOCUMENTO', models.IntegerField(db_column='CIDCONCEPTODOCUMENTO')),
                ('CFOLIO', models.FloatField(db_column='CFOLIO')),
                ('CFECHA', models.DateTimeField(db_column='CFECHA')),
                ('CIDCLIENTEPROVEEDOR', models.IntegerField(db_column='CIDCLIENTEPROVEEDOR')),
                ('CRAZONSOCIAL', models.CharField(db_column='CRAZONSOCIAL', max_length=200, null=True)),
                ('CIDAGENTE', models.IntegerField(db_column='CIDAGENTE')),
                ('CFECHAVENCIMIENTO', models.DateTimeField(db_column='CFECHAVENCIMIENTO', null=True)),
                ('CPENDIENTE', models.FloatField(db_column='CPENDIENTE')),
                ('CCANCELADO', models.IntegerField(db_column='CCANCELADO')),
                ('CREFERENCIA', models.CharField(db_column='CREFERENCIA', max_length=200, null=True)),
                ('CTOTAL', models.FloatField(db_column='CTOTAL', null=True)),
            ],
            options={
                'db_table': 'admDocumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmMovimientos',
            fields=[
                ('CIDMOVIMIENTO', models.AutoField(db_column='CIDMOVIMIENTO', primary_key=True, serialize=False)),
                ('CIDDOCUMENTO', models.IntegerField(db_column='CIDDOCUMENTO')),
                ('CIDDOCUMENTODE', models.IntegerField(db_column='CIDDOCUMENTODE')),
                ('CIDPRODUCTO', models.IntegerField(db_column='CIDPRODUCTO')),
                ('CUNIDADES', models.FloatField(db_column='CUNIDADES')),
                ('CNETO', models.FloatField(db_column='CNETO')),
                ('CTOTAL', models.FloatField(db_column='CTOTAL')),
            ],
            options={
                'db_table': 'admMovimientos',
                'managed': False,
            },
        ),
    ]
