# Generated by Django 6.0.7 on 2026-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admagentes_admconceptos_admdocumentos_admmovimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmClientes',
            fields=[
                ('CIDCLIENTEPROVEEDOR', models.AutoField(db_column='CIDCLIENTEPROVEEDOR', primary_key=True, serialize=False)),
                ('CRAZONSOCIAL', models.CharField(db_column='CRAZONSOCIAL', max_length=200, null=True)),
            ],
            options={
                'db_table': 'admClientes',
                'managed': False,
            },
        ),
    ]
