# Generated by Django 6.0.7 on 2026-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(max_length=150)),
                ('target_username', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('CREATED', 'Cuenta creada'), ('ROLE_CHANGED', 'Rol cambiado'), ('ZONE_CHANGED', 'Zona cambiada'), ('ACTIVATED', 'Cuenta activada'), ('DEACTIVATED', 'Cuenta desactivada'), ('PASSWORD_RESET', 'Contraseña restablecida')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.CharField(blank=True, choices=[('ZONA1', 'Zona 1'), ('ZONA2', 'Zona 2'), ('OFICINA', 'Oficina'), ('SERVICIOS', 'Servicios'), ('PUNTOVENTA', 'Punto de Venta')], max_length=10),
        ),
    ]
