# Generated by Django 6.0.7 on 2026-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountauditlogentry_profile_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SALESPERSON', 'Vendedor'), ('ACCOUNTING', 'Contabilidad'), ('MANAGEMENT', 'Gerencia')], default='SALESPERSON', max_length=20),
        ),
    ]
