# Generated by Django 6.0.7 on 2026-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(db_index=True, max_length=30)),
                ('file', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['producto_codigo', 'order'],
            },
        ),
    ]
