# Generated by Django 6.0.7 on 2026-09-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(max_length=30, unique=True)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['producto_codigo'],
            },
        ),
    ]
