# Generated by Django 6.0.7 on 2026-10-01 19:03

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productpricevisibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=catalog.models._new_token, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'Nueva'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='NEW', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.quoterequest')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('request', 'producto_codigo')},
            },
        ),
    ]
