# Generated by Django 6.0.7 on 2026-09-15 16:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_seed_rates_and_zero_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioncategoryrate',
            name='decay_rate_per_week',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0050'), max_digits=5),
        ),
    ]
