# Generated by Django 6.0.7 on 2026-09-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_seed_puntoventa_rate_and_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoventaclientzone',
            options={'ordering': ['cliente_id']},
        ),
        migrations.RemoveField(
            model_name='puntoventaclientzone',
            name='cliente_nombre',
        ),
    ]
