# Generated by Django 6.0.7 on 2026-10-03 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Management 2026-10-03, bare ERP ids only (the repo is public). 632 and 11
# are relatives of a Punto de Venta owner: PV prices, and so the PV rate, on
# powdered milk only (632 was already listed with every product, which never
# applied - his invoices are under Zona 1, not Punto de Venta). 1499 and 1379
# are Punto de Venta clients registered under Zona 2 in the ERP.
POWDERED_MILK = 'BIO-SLC1,BIO-SLC2,BIO-SPRI'
CLIENTS = [
    (632, 'ZONA1', POWDERED_MILK),
    (11, 'ZONA1', POWDERED_MILK),
    (1499, 'ZONA2', ''),
    (1379, 'ZONA2', ''),
]


def seed(apps, schema_editor):
    PuntoVentaClientZone = apps.get_model('commissions', 'PuntoVentaClientZone')
    for cliente_id, zone, product_codes in CLIENTS:
        PuntoVentaClientZone.objects.update_or_create(
            cliente_id=cliente_id,
            defaults={'zone': zone, 'product_codes': product_codes, 'note': 'Management 2026-10-03'},
        )


def unseed(apps, schema_editor):
    PuntoVentaClientZone = apps.get_model('commissions', 'PuntoVentaClientZone')
    PuntoVentaClientZone.objects.filter(cliente_id__in=[11, 1499, 1379]).delete()
    PuntoVentaClientZone.objects.filter(cliente_id=632).update(product_codes='')



class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_puntoventa_oficina_and_last_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventaclientzone',
            name='product_codes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LineRateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento_id', models.IntegerField(unique=True)),
                ('invoice_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
