# Generated by Django 6.0.7 on 2026-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte_de_caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortedecajaadjustment',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cortedecajaadjustment',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
